### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by luantunez** [derEitel/explainableMS#1]
Thank you and very much for sharing your great work!
Would it be possible for you to share with me the checkpoint for the pretrained model?
Thank you in advance, 
Lucía

**Comment by derEitel** [comment]
Hi Lucía,
due to the risk of extracting information about the private data set that was used we cannot share the model checkpoints publicly. Potentially, that could be possible in a scientific collaboration (also a thesis for example). If you are interested in that feel free to send me an email: fabian.eitel@bccn-berlin.de
Best,
Fabi
